### PR TITLE
Create Typography “1-01-typography-test-entry-1”

### PR DESCRIPTION
**Pull request by devinea**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by devinea** [comment]
@ruaraikirk - can you update with json from @tborychowski ?

**Comment by ruaraikirk** [comment]
@devinea Can do. However there is one group of text styles in the data that @tborychowski provided which have colors that are not hex values. E.g. :
`      "name": "Kpi's",
        "styles": [
            {
                "name": "KPI",
                "uppercase": false,
                "style": "Light",
                "size": 48,
                "height": 60,
                "color": "Semantic"
            },`
I'm not sure if we can amend/update the field's widget to accept either hex or string values...

**Comment by ruaraikirk** [comment]
Data updated.

**Comment by devinea** [comment]
Thanks @ruaraikirk 

@tborychowski - is that valid data ? 
`"name": "Kpi's", "styles": [ { "name": "KPI", "uppercase": false, "style": "Light", "size": 48, "height": 60, "color": "Semantic" },`

**Comment by devinea** [comment]
@ruaraikirk I can't approve PR. But 👍 for me.

**Pull request merged**
