### PR TITLE
Add video plugin

### PR DESCRIPTION
**Pull request by ritarora**
Add a plugin to embed a video on design pages

### CODE REVIEW

**Comment by devinea** [comment]
@ritarora 
So in the markdown we add something like this ?
`vimeo https://vimeo.com/261899430`

Do we need the options mentioned in https://www.gatsbyjs.org/packages/gatsby-remark-embed-video/#install ?

Would be nice to add a netlify cms widget for this also https://www.netlifycms.org/docs/custom-widgets/

**Comment by ritarora** [comment]
@devinea added the sample code

To add a responsive video we need to add 
<iframe src="https://player.vimeo.com/video/261899430" class ='embedVideoIframe'></iframe>
and add the css in the class and not hardcode any in the options in the plugin

**Comment by eouin** [comment]
@ritarora @devinea I reckon we should add a custom widget to allow people to add a video like described at https://www.netlifycms.org/docs/custom-widgets/
I've added the youtube snippet code to /src/cms/cms.js and it worked. I can now choose a youtube video directly from the widget toolbar

**Comment by ritarora** [comment]
Closing this PR as created a new one https://github.com/devinea/mvx19-cms/pull/35

**Pull request closed without merging**
